replicaCount: 1

image:
  repository: orcrist-server # Local image built from challenge-3/Dockerfile
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

container:
  port: 8080

resources: {}
